spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/workspace
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug

jwt:
  secret: "d9vFf3h+6B23jw5jHgmQ0uFykJrO42nWOpjUV8IdNgI="
  expiration: 43200